### ISSUE TITLE
Move containerLoginForm

### ISSUE THREAD

**Issue by d4ins** [AntonSkovpen/to-do-list#5]
- [x] Move `containerLoginForm` to `containers` and name folder name appropriate  (if this is a component it should start from large letter)
- [x] Also rename nested files correctly.
- [x] And  if this will be already in container folder, then you can just name it as `Login` (since `container` is used for describing application page, so for example if you have login page then you should have `container/Login`, if you have todo list page then you should have `container/TodoList` etc)

**Comment by AntonSkovpen** [comment]
fixed
